name=05.24GRadio
version=0.1.1
author=CHIP-PUMP CP8000 Arduino SDK contributors
maintainer=v7idea
sentence=CHIP-PUMP CP8000 05.24GRadio examples.
paragraph=Categorized CP8000 Arduino examples for the CHIP-PUMP CP8000 Boards package.
category=Other
url=https://github.com/v7idea/chip-pump-cp8000
architectures=cp8000
